[package]
name = "gimage-resize-rust"
version = "0.1.0"
edition = "2018"
authors = ["Ivan Chepurnyi <ivan.chepurnyi@ecomdev.org>"]

[dependencies]
serde_json = "1.0.39"
serde = "1.0.90"
serde_derive = "1.0.90"
tokio = "0.1.19"
futures = "0.1.26"